# syntax=docker/dockerfile:1
FROM python:3

# 環境変数設定
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 作業ディレクトリ設定
WORKDIR /project

# 依存関係をコピー
COPY requirements.txt /project/

# 必要なパッケージのインストール
RUN apt-get update && apt-get install -y && \
    rm -rf /var/lib/apt/lists/*

# Python パッケージのインストール
RUN pip install -r requirements.txt && \
    pip install -U 'channels[daphne]' && \
    pip install django-friendship \
                django-rainbowtests \
                Pillow

# アプリケーションファイルをコピー
COPY . /project/

# セレニウムなしのバージョン