# Generated by Django 4.2 on 2025-01-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='accounts/images/gnu.png', upload_to='accounts/images'),
        ),
    ]
