# Generated by Django 4.2 on 2025-02-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_totp_secret_user_use_totp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='use_totp',
            field=models.BooleanField(default=False),
        ),
    ]
