# Generated by Django 4.2 on 2025-01-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
