# Generated by Django 4.2 on 2025-03-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_alter_matchhistory_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchHistory',
        ),
    ]
