# Generated by Django 4.2 on 2025-03-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='type',
            field=models.IntegerField(choices=[(0, 'round-robin'), (1, 'single-elimination')], default=0),
            preserve_default=False,
        ),
    ]
