# Generated by Django 4.2 on 2025-03-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_delete_matchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
