# Generated by Django 4.2.11 on 2025-01-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, height_field=50, upload_to='accounts/images', width_field=50),
        ),
    ]
