# Generated by Django 4.2 on 2025-03-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('friendship', '0004_auto_20200408_1844'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('pong', '0002_alter_matchhistory_date'),
        ('accounts', '0010_customuser_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
